use std::{collections::HashSet, time::Duration};

use axum::{
    Extension, Json,
    extract::State,
    http::header,
    response::{IntoResponse, Response},
};
use serde::{Deserialize, Serialize};
use sqlx::{FromRow, SqlitePool};
use uuid::Uuid;

use crate::{AppError, AppState, auth::UserIdentity, meta, require_root, valid_origin};

const SYNC_INTERVAL: Duration = Duration::from_secs(60);
const MAX_RESPONSE_BYTES: usize = 32 * 1024 * 1024;

#[derive(Serialize, FromRow)]
struct SyncStatus {
    configured: bool,
    last_synced_at: Option<i64>,
    user_count: i64,
    last_error: Option<String>,
}

async fn status(db: &SqlitePool) -> Result<Response, AppError> {
    let status: SyncStatus = sqlx::query_as(
        "SELECT token<>'' AS configured,last_synced_at,user_count,last_error FROM auth_directory_sync WHERE id=1",
    ).fetch_one(db).await?;
    Ok(([(header::CACHE_CONTROL, "no-store")], Json(status)).into_response())
}

pub(crate) async fn get_settings(
    State(state): State<AppState>,
    Extension(user): Extension<UserIdentity>,
) -> Result<Response, AppError> {
    require_root(&state.db, &user.id).await?;
    status(&state.db).await
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SettingsInput {
    token: String,
}

pub(crate) async fn save_settings(
    State(state): State<AppState>,
    Extension(user): Extension<UserIdentity>,
    Json(input): Json<SettingsInput>,
) -> Result<Response, AppError> {
    require_root(&state.db, &user.id).await?;
    let token = input.token.trim();
    if token.len() != 71
        || !token.starts_with("am_uid_")
        || !token.as_bytes()[7..].iter().all(u8::is_ascii_hexdigit)
    {
        return Err(AppError::bad_request(
            "enter a user ID directory token generated by Auth Mini",
        ));
    }
    let _guard = state.directory_sync_lock.lock().await;
    sync_and_save(&state.db, token).await?;
    status(&state.db).await
}

pub(crate) async fn clear_settings(
    State(state): State<AppState>,
    Extension(user): Extension<UserIdentity>,
) -> Result<Response, AppError> {
    require_root(&state.db, &user.id).await?;
    let _guard = state.directory_sync_lock.lock().await;
    sqlx::query("UPDATE auth_directory_sync SET token='',last_error=NULL WHERE id=1")
        .execute(&state.db)
        .await?;
    status(&state.db).await
}

pub(crate) async fn sync_now(
    State(state): State<AppState>,
    Extension(user): Extension<UserIdentity>,
) -> Result<Response, AppError> {
    require_root(&state.db, &user.id).await?;
    let _guard = state.directory_sync_lock.lock().await;
    let token = saved_token(&state.db).await?;
    if token.is_empty() {
        return Err(AppError::bad_request(
            "configure an Auth Mini directory token first",
        ));
    }
    sync_saved(&state.db, &token).await?;
    status(&state.db).await
}

async fn saved_token(db: &SqlitePool) -> Result<String, AppError> {
    Ok(
        sqlx::query_scalar("SELECT token FROM auth_directory_sync WHERE id=1")
            .fetch_one(db)
            .await?,
    )
}

pub(crate) fn schedule(state: AppState) {
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(SYNC_INTERVAL);
        interval.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
        loop {
            interval.tick().await;
            if let Err(error) = sync_configured(&state).await {
                tracing::warn!(%error, "Auth Mini user ID directory sync failed");
            }
        }
    });
}

async fn sync_configured(state: &AppState) -> Result<(), AppError> {
    let _guard = state.directory_sync_lock.lock().await;
    let token = saved_token(&state.db).await?;
    if token.is_empty() {
        return Ok(());
    }
    sync_saved(&state.db, &token).await
}

async fn sync_saved(db: &SqlitePool, token: &str) -> Result<(), AppError> {
    let result = sync_and_save(db, token).await;
    if let Err(error) = &result {
        // RECOVERY: report a scheduled/manual sync failure to the administrator;
        // keep the previous successful snapshot and retry on the next timer tick.
        sqlx::query("UPDATE auth_directory_sync SET last_error=? WHERE id=1")
            .bind(&error.message)
            .execute(db)
            .await?;
    }
    result
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct UserIds {
    user_ids: Vec<String>,
}

async fn fetch_user_ids(issuer: &str, token: &str) -> Result<Vec<String>, AppError> {
    let issuer = valid_origin(issuer, "Auth Mini issuer")?;
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(15))
        .redirect(reqwest::redirect::Policy::none())
        .build()
        .map_err(|_| AppError::unavailable("cannot initialize Auth Mini directory client"))?;
    let mut response = client
        .get(format!("{issuer}/integration/user-ids"))
        .bearer_auth(token)
        .send()
        .await
        .map_err(|_| AppError::unavailable("Auth Mini directory is unreachable"))?;
    if response.status() == reqwest::StatusCode::UNAUTHORIZED {
        return Err(AppError::bad_request(
            "Auth Mini directory token is invalid or revoked",
        ));
    }
    if response.status() != reqwest::StatusCode::OK {
        return Err(AppError::unavailable(format!(
            "Auth Mini directory returned HTTP {}",
            response.status().as_u16(),
        )));
    }
    let mut body = Vec::new();
    while let Some(chunk) = response
        .chunk()
        .await
        .map_err(|_| AppError::unavailable("could not read the complete Auth Mini directory"))?
    {
        if body.len() + chunk.len() > MAX_RESPONSE_BYTES {
            return Err(AppError::unavailable(
                "Auth Mini directory exceeds the 32 MiB response limit",
            ));
        }
        body.extend_from_slice(&chunk);
    }
    let mut ids = serde_json::from_slice::<UserIds>(&body)
        .map_err(|_| AppError::unavailable("Auth Mini directory response is invalid"))?
        .user_ids;
    for id in &ids {
        let parsed = Uuid::parse_str(id).map_err(|_| {
            AppError::unavailable("Auth Mini directory contains an invalid user ID")
        })?;
        if parsed.to_string() != *id {
            return Err(AppError::unavailable(
                "Auth Mini directory contains a non-canonical user ID",
            ));
        }
    }
    ids.sort_unstable();
    ids.dedup();
    Ok(ids)
}

async fn sync_and_save(db: &SqlitePool, token: &str) -> Result<(), AppError> {
    let ids = fetch_user_ids(&meta(db, "auth_issuer").await?, token).await?;
    let now = chrono::Utc::now().timestamp();
    let mut tx = db.begin().await?;
    let bots: HashSet<String> = sqlx::query_scalar("SELECT id FROM users WHERE type='bot'")
        .fetch_all(&mut *tx)
        .await?
        .into_iter()
        .collect();
    for id in &ids {
        if bots.contains(id) {
            return Err(AppError::conflict(
                "Auth Mini user ID conflicts with a Linkit Bot",
            ));
        }
        sqlx::query(
            "INSERT INTO users(id,type,created_at) VALUES(?,'human',?) ON CONFLICT(id) DO NOTHING",
        )
        .bind(id)
        .bind(now)
        .execute(&mut *tx)
        .await?;
    }
    sqlx::query("UPDATE auth_directory_sync SET token=?,last_synced_at=?,user_count=?,last_error=NULL WHERE id=1")
        .bind(token).bind(now).bind(ids.len() as i64).execute(&mut *tx).await?;
    tx.commit().await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use axum::{
        Router,
        body::Body,
        extract::Query,
        http::{HeaderMap, StatusCode},
        routing::get,
    };
    use http_body_util::BodyExt;
    use serde_json::{Value, json};
    use tokio::sync::RwLock;
    use tower::ServiceExt;

    use super::*;

    const ROOT: &str = "00000000-0000-4000-8000-000000000001";
    const NEW_USER: &str = "00000000-0000-4000-8000-000000000002";
    const BOT: &str = "00000000-0000-4000-8000-000000000003";
    fn token() -> String {
        format!("am_uid_{}", "a".repeat(64))
    }
    fn root() -> Extension<UserIdentity> {
        Extension(UserIdentity {
            id: ROOT.to_owned(),
        })
    }

    async fn fixture() -> (AppState, Arc<RwLock<(StatusCode, Value)>>) {
        let db = crate::db::connect_memory().await.unwrap();
        sqlx::query("UPDATE app_meta SET value=? WHERE key='root_user_id'")
            .bind(ROOT)
            .execute(&db)
            .await
            .unwrap();
        sqlx::query("INSERT INTO users(id,created_at) VALUES(?,1)")
            .bind(ROOT)
            .execute(&db)
            .await
            .unwrap();
        let payload = Arc::new(RwLock::new((
            StatusCode::OK,
            json!({"user_ids": [ROOT, NEW_USER]}),
        )));
        let response = payload.clone();
        let upstream = Router::new().route(
            "/integration/user-ids",
            get(move |headers: HeaderMap| {
                let response = response.clone();
                async move {
                    if headers
                        .get(header::AUTHORIZATION)
                        .and_then(|value| value.to_str().ok())
                        != Some(format!("Bearer {}", token()).as_str())
                    {
                        return (
                            StatusCode::UNAUTHORIZED,
                            Json(json!({"error": "invalid_directory_token"})),
                        );
                    }
                    let (status, payload) = response.read().await.clone();
                    (status, Json(payload))
                }
            }),
        );
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let issuer = format!("http://{}", listener.local_addr().unwrap());
        tokio::spawn(async move {
            axum::serve(listener, upstream).await.unwrap();
        });
        sqlx::query("UPDATE app_meta SET value=? WHERE key='auth_issuer'")
            .bind(issuer)
            .execute(&db)
            .await
            .unwrap();
        (crate::tests::test_state(db), payload)
    }

    async fn payload(response: Response) -> Value {
        serde_json::from_slice(&response.into_body().collect().await.unwrap().to_bytes()).unwrap()
    }

    #[tokio::test]
    async fn save_syncs_all_ids_idempotently_without_overwriting_or_deleting_local_data() {
        let (state, upstream) = fixture().await;
        sqlx::query("INSERT INTO profiles(user_id,username,intro,updated_at) VALUES(?,'Root profile','keep this',1)").bind(ROOT).execute(&state.db).await.unwrap();
        sqlx::query(
            "INSERT INTO users(id,type,created_at) VALUES(?,'bot',1),('historical-user','human',1)",
        )
        .bind(BOT)
        .execute(&state.db)
        .await
        .unwrap();
        let response = save_settings(
            State(state.clone()),
            root(),
            Json(SettingsInput { token: token() }),
        )
        .await
        .unwrap();
        assert_eq!(response.headers()[header::CACHE_CONTROL], "no-store");
        let status = payload(response).await;
        assert_eq!(status["configured"], true);
        assert_eq!(status["user_count"], 2);
        assert!(status["last_synced_at"].is_number());
        assert!(status.get("token").is_none());
        assert!(!status.to_string().contains(&token()));
        sync_now(State(state.clone()), root()).await.unwrap();
        let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM users")
            .fetch_one(&state.db)
            .await
            .unwrap();
        assert_eq!(count, 4);
        let profile: String = sqlx::query_scalar("SELECT intro FROM profiles WHERE user_id=?")
            .bind(ROOT)
            .fetch_one(&state.db)
            .await
            .unwrap();
        assert_eq!(profile, "keep this");
        let user_type: String = sqlx::query_scalar("SELECT type FROM users WHERE id=?")
            .bind(BOT)
            .fetch_one(&state.db)
            .await
            .unwrap();
        assert_eq!(user_type, "bot");
        let results = crate::search_users(
            State(state.clone()),
            Query(crate::UserQuery {
                query: Some(NEW_USER.to_owned()),
            }),
        )
        .await
        .unwrap()
        .0;
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].user_id, NEW_USER);
        assert_eq!(results[0].username, NEW_USER);
        assert!(results[0].avatar_url.is_none());
        *upstream.write().await = (StatusCode::OK, json!({"user_ids": []}));
        sync_configured(&state).await.unwrap();
        let count_after: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM users")
            .fetch_one(&state.db)
            .await
            .unwrap();
        assert_eq!(count_after, count);
        assert_eq!(
            payload(get_settings(State(state.clone()), root()).await.unwrap()).await["user_count"],
            0
        );
        clear_settings(State(state.clone()), root()).await.unwrap();
        assert_eq!(saved_token(&state.db).await.unwrap(), "");
        *upstream.write().await = (StatusCode::INTERNAL_SERVER_ERROR, json!({}));
        sync_configured(&state).await.unwrap();
        assert_eq!(
            sync_now(State(state), root()).await.unwrap_err().status,
            StatusCode::BAD_REQUEST
        );
    }

    #[tokio::test]
    async fn only_root_can_read_save_clear_or_trigger_sync() {
        let (state, _) = fixture().await;
        let stranger = || {
            Extension(UserIdentity {
                id: NEW_USER.to_owned(),
            })
        };
        assert_eq!(
            get_settings(State(state.clone()), stranger())
                .await
                .unwrap_err()
                .status,
            StatusCode::FORBIDDEN
        );
        assert_eq!(
            save_settings(
                State(state.clone()),
                stranger(),
                Json(SettingsInput { token: token() })
            )
            .await
            .unwrap_err()
            .status,
            StatusCode::FORBIDDEN
        );
        assert_eq!(
            clear_settings(State(state.clone()), stranger())
                .await
                .unwrap_err()
                .status,
            StatusCode::FORBIDDEN
        );
        assert_eq!(
            sync_now(State(state.clone()), stranger())
                .await
                .unwrap_err()
                .status,
            StatusCode::FORBIDDEN
        );
        for (method, path) in [
            ("GET", "/api/admin/auth-mini-directory"),
            ("PUT", "/api/admin/auth-mini-directory"),
            ("DELETE", "/api/admin/auth-mini-directory"),
            ("POST", "/api/admin/auth-mini-directory/sync"),
        ] {
            let response = crate::router(state.clone())
                .oneshot(
                    axum::http::Request::builder()
                        .method(method)
                        .uri(path)
                        .body(Body::empty())
                        .unwrap(),
                )
                .await
                .unwrap();
            assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
        }
    }

    #[tokio::test]
    async fn malformed_revoked_and_truncated_snapshots_leave_the_previous_state_untouched() {
        let (state, upstream) = fixture().await;
        save_settings(
            State(state.clone()),
            root(),
            Json(SettingsInput { token: token() }),
        )
        .await
        .unwrap();
        let before = payload(get_settings(State(state.clone()), root()).await.unwrap()).await;
        for (status, body) in [
            (
                StatusCode::UNAUTHORIZED,
                json!({"error":"invalid_directory_token"}),
            ),
            (StatusCode::INTERNAL_SERVER_ERROR, json!({})),
            (StatusCode::OK, json!({})),
            (StatusCode::OK, json!({"user_ids":[ROOT, "invalid"]})),
            (
                StatusCode::OK,
                json!({"user_ids": [ROOT], "email": "must-not-import@example.com"}),
            ),
        ] {
            *upstream.write().await = (status, body);
            assert!(sync_now(State(state.clone()), root()).await.is_err());
            let after = payload(get_settings(State(state.clone()), root()).await.unwrap()).await;
            assert_eq!(after["last_synced_at"], before["last_synced_at"]);
            assert_eq!(after["user_count"], before["user_count"]);
            assert!(after["last_error"].is_string());
            assert!(!after.to_string().contains(&token()));
            assert_eq!(saved_token(&state.db).await.unwrap(), token());
        }
        *upstream.write().await = (StatusCode::OK, json!({"user_ids": [ROOT, NEW_USER]}));
        sync_configured(&state).await.unwrap();
        assert!(
            payload(get_settings(State(state), root()).await.unwrap()).await["last_error"]
                .is_null()
        );
    }

    #[tokio::test]
    async fn invalid_replacement_never_overwrites_the_saved_token() {
        let (state, _) = fixture().await;
        save_settings(
            State(state.clone()),
            root(),
            Json(SettingsInput { token: token() }),
        )
        .await
        .unwrap();
        for invalid in [
            "a.jwt.token".to_owned(),
            "".to_owned(),
            format!("am_uid_{}", "b".repeat(64)),
        ] {
            assert!(
                save_settings(
                    State(state.clone()),
                    root(),
                    Json(SettingsInput { token: invalid })
                )
                .await
                .is_err()
            );
            assert_eq!(saved_token(&state.db).await.unwrap(), token());
        }
        let public = payload(
            crate::public_config(State(state))
                .await
                .unwrap()
                .into_response(),
        )
        .await;
        assert!(!public.to_string().contains("am_uid_"));
    }

    #[tokio::test]
    async fn bot_id_conflict_rolls_back_the_entire_import() {
        let (state, upstream) = fixture().await;
        sqlx::query("INSERT INTO users(id,type,created_at) VALUES(?,'bot',1)")
            .bind(BOT)
            .execute(&state.db)
            .await
            .unwrap();
        *upstream.write().await = (StatusCode::OK, json!({"user_ids": [NEW_USER, BOT]}));
        assert_eq!(
            save_settings(
                State(state.clone()),
                root(),
                Json(SettingsInput { token: token() })
            )
            .await
            .unwrap_err()
            .status,
            StatusCode::CONFLICT
        );
        let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM users WHERE id=?")
            .bind(NEW_USER)
            .fetch_one(&state.db)
            .await
            .unwrap();
        assert_eq!(count, 0);
        assert!(saved_token(&state.db).await.unwrap().is_empty());
    }

    #[tokio::test]
    async fn user_id_search_uses_the_users_nocase_index() {
        let db = crate::db::connect_memory().await.unwrap();
        let plan: Vec<(i64, i64, i64, String)> = sqlx::query_as(
            "EXPLAIN QUERY PLAN SELECT u.id,p.username FROM users u LEFT JOIN profiles p ON p.user_id=u.id WHERE u.id LIKE ? COLLATE NOCASE"
        ).bind("0000%").fetch_all(&db).await.unwrap();
        assert!(plan.iter().any(|row| row.3.contains("users_id_nocase")));
    }

    #[tokio::test]
    async fn directory_client_does_not_follow_redirects_or_send_tokens_to_another_endpoint() {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let issuer = format!("http://{}", listener.local_addr().unwrap());
        let visited = Arc::new(std::sync::atomic::AtomicBool::new(false));
        let trap_visited = visited.clone();
        let upstream = Router::new()
            .route(
                "/integration/user-ids",
                get(|| async { axum::response::Redirect::temporary("/trap") }),
            )
            .route(
                "/trap",
                get(move || {
                    let visited = trap_visited.clone();
                    async move {
                        visited.store(true, std::sync::atomic::Ordering::SeqCst);
                        Json(json!({"user_ids": []}))
                    }
                }),
            );
        tokio::spawn(async move {
            axum::serve(listener, upstream).await.unwrap();
        });
        assert!(fetch_user_ids(&issuer, &token()).await.is_err());
        assert!(!visited.load(std::sync::atomic::Ordering::SeqCst));
    }
}
